name: Debug SSH
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH Connection
        run: |
          # SSH設定
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # 鍵のフィンガープリントを確認
          echo "=== Key fingerprint ==="
          ssh-keygen -lf ~/.ssh/id_rsa
          
          # 詳細な接続ログ
          echo "=== Connection test with verbose mode ==="
          ssh -vvv -p ${{ secrets.SSH_PORT }} \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -i ~/.ssh/id_rsa \
              ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
              "echo 'Success!'" || echo "Failed with exit code: $?"
